export const API_REQUEST = 'API_REQUEST';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAILURE = 'API_FAILURE';

export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN';
export const TOGGLE_EDITING = 'TOGGLE_EDITING';
export const SET_EDITING = 'SET_EDITING';
export const LOAD_ACCOUNT_DATA = 'LOAD_ACCOUNT_DATA';